# Generated by Django 5.1.3 on 2024-11-16 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_address_profile_avatar_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_newsletters',
            field=models.BooleanField(default=True, verbose_name='Получать новости и акции'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления о заказах'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number'], name='accounts_pr_phone_n_c27a97_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['birth_date'], name='accounts_pr_birth_d_002f13_idx'),
        ),
    ]
