# Generated by Django 5.1.3 on 2024-11-13 10:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at_product_stock_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 11, 13, 10, 22, 30, 62686, tzinfo=datetime.timezone.utc), max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 11, 13, 10, 22, 53, 661905, tzinfo=datetime.timezone.utc), max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
