# Generated by Django 5.1.3 on 2024-12-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
