# Generated by Django 5.1.3 on 2024-12-10 09:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое'),
        ),
    ]
